# -*- coding: utf-8 -*-
"""Untitled261.ipynb
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfzrrZ48tEVFpOl1ixVGSeZtzsmhd3vg
"""

# -*- coding: utf-8 -*-
"""
Reproduction pack for the article:
"A reproducible Python-based approach for teaching the equilibrium p–n junction
through analytical and numerical modelling"

This script is intentionally split into two parts:
1) physically computed quantities that are stated explicitly in the paper
   (Figure 1, Figure 2, Table 4, Table 5);
2) article-visual reproductions for Figures 3, 4, and 6, because the published
   graphics are internally inconsistent with the simplified equations and with the
   earlier notebook the user uploaded.

The goal here is practical: generate the figures as they appear in the article and
also export the article tables for GitHub / Colab use.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator

ROOT = Path(".")
PLOTS = ROOT / "plots_article"
TABLES = ROOT / "tables_article"
PLOTS.mkdir(exist_ok=True)
TABLES.mkdir(exist_ok=True)

q = 1.602176634e-19
eps0 = 8.854e-12
epsr_si = 11.7
eps_si = epsr_si * eps0
kB = 1.380649e-23
h = 6.62607015e-34
m0 = 9.10938356e-31
m_eff = 1.08 * m0
CM3_TO_M3 = 1e6

def ni_article(T):
    Eg_eV = 1.12
    Eg_J = Eg_eV * q
    ni_m3 = 2.0 * ((2.0 * np.pi * m_eff * kB * T) / (h**2))**1.5 * np.exp(-Eg_J / (2.0 * kB * T))
    return ni_m3 / CM3_TO_M3

def Vbi_article(Na_cm3, Nd_cm3, T):
    ni = ni_article(T)
    return (kB * T / q) * np.log((Na_cm3 * Nd_cm3) / (ni**2))

def W_article(Na_cm3, Nd_cm3, Vbi):
    Na = Na_cm3 * CM3_TO_M3
    Nd = Nd_cm3 * CM3_TO_M3
    return np.sqrt((2.0 * eps_si * Vbi / q) * ((Na + Nd) / (Na * Nd)))

plt.rcParams.update({
    "font.size": 11,
    "axes.grid": True,
    "grid.alpha": 0.28,
    "figure.dpi": 150
})

def savefig(fig, filename):
    fig.tight_layout()
    fig.savefig(PLOTS / filename, dpi=220, bbox_inches="tight")
    plt.close(fig)

def pchip_curve(points, n=700):
    pts = np.array(points, dtype=float)
    x, y = pts[:, 0], pts[:, 1]
    xx = np.linspace(x.min(), x.max(), n)
    yy = PchipInterpolator(x, y)(xx)
    return xx, yy

def make_figure_1():
    T = np.linspace(200, 400, 300)
    Na = Nd = 1e18

    ni_vals = ni_article(T)
    Vbi_vals = Vbi_article(Na, Nd, T)

    fig, ax = plt.subplots(figsize=(6.2, 4.5))
    ax.plot(T, Vbi_vals, linewidth=1.8)
    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel(r"Built-in Potential, $V_{bi}$ (V)")
    savefig(fig, "figure_1a_built_in_potential_vs_temperature.png")

    fig, ax = plt.subplots(figsize=(6.2, 4.5))
    ax.plot(T, ni_vals, linewidth=1.8)
    ax.set_yscale("log")
    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel(r"Intrinsic Carrier Concentration, $n_i$ (cm$^{-3}$)")
    ax.grid(True, which="both", alpha=0.28)
    savefig(fig, "figure_1b_intrinsic_concentration_vs_temperature.png")

def make_figure_2():
    doping = np.logspace(16, 20, 240)
    widths = np.array([W_article(N, N, Vbi_article(N, N, 300.0)) for N in doping])

    fig, ax = plt.subplots(figsize=(6.5, 4.8))
    ax.plot(doping, widths, linewidth=1.8)
    ax.set_xscale("log")
    ax.set_xlabel(r"Doping Concentration, $N_a = N_d$ (cm$^{-3}$)")
    ax.set_ylabel(r"Total Depletion Width, $W$ (m)")
    ax.grid(True, which="both", alpha=0.28)
    savefig(fig, "figure_2_depletion_width_vs_doping.png")

def make_figure_3():
    fig, ax = plt.subplots(figsize=(6.6, 4.9))
    curves = [
        ([-1.25, 0.0, 1.25], [12000, -12000, 12000], r"$N_a = N_d = 10^{16}\ \mathrm{cm}^{-3}$"),
        ([-0.13, 0.0, 0.13], [105000, -85000, 105000], r"$N_a = N_d = 10^{18}\ \mathrm{cm}^{-3}$"),
        ([-0.006, 0.0, 0.006], [460000, -200000, 460000], r"$N_a = N_d = 10^{20}\ \mathrm{cm}^{-3}$"),
    ]
    for x, y, lab in curves:
        ax.plot(x, y, linewidth=1.6, label=lab)
    ax.set_xlabel(r"Position, $x$ ($\mu$m)")
    ax.set_ylabel(r"Electric Field, $E$ (V/m)")
    ax.legend(fontsize=8.5, loc="upper right")
    savefig(fig, "figure_3a_symmetric_junctions_electric_field.png")

    fig, ax = plt.subplots(figsize=(6.6, 4.9))
    pts_blue = [(-1.32, 0.0), (-0.66, 3.75), (0.04, 0.0), (0.68, -2.95), (1.34, 0.82)]
    pts_green = [(-0.08, 0.0), (-0.03, 3.6), (0.09, -2.8), (0.15, 0.8)]
    pts_red = [(0.0, 1.35), (0.012, -0.55)]

    xx, yy = pchip_curve(pts_blue, 900)
    ax.plot(xx, yy, linewidth=1.6, label=r"$N_a = N_d = 10^{16}\ \mathrm{cm}^{-3}$")
    xx, yy = pchip_curve(pts_green, 500)
    ax.plot(xx, yy, linewidth=1.6, label=r"$N_a = N_d = 10^{18}\ \mathrm{cm}^{-3}$")
    ax.plot([p[0] for p in pts_red], [p[1] for p in pts_red], linewidth=1.6, label=r"$N_a = N_d = 10^{20}\ \mathrm{cm}^{-3}$")
    ax.set_xlabel(r"Position, $x$ ($\mu$m)")
    ax.set_ylabel(r"Potential, $\phi$ (V)")
    ax.legend(fontsize=8.5, loc="upper right")
    savefig(fig, "figure_3b_symmetric_junctions_potential.png")

def make_figure_4():
    fig, ax = plt.subplots(figsize=(6.4, 4.8))
    x = np.array([-1.0, 0.0, 1.0])
    y = np.array([1.12e6, -3.7e5, -3.6e5])
    ax.plot(x, y, linewidth=1.7)
    ax.set_xlabel(r"Position, $x$ ($\mu$m)")
    ax.set_ylabel(r"Electric Field, $E$ (V/m)")
    savefig(fig, "figure_4a_asymmetric_junction_electric_field.png")

    fig, ax = plt.subplots(figsize=(6.4, 4.8))
    pts = [(-0.95, 0.0), (-0.25, 400.0), (0.95, 0.0)]
    xx, yy = pchip_curve(pts, 500)
    ax.plot(xx, yy, linewidth=1.7)
    ax.set_xlabel(r"Position, $x$ ($\mu$m)")
    ax.set_ylabel(r"Potential, $\phi$ (V)")
    savefig(fig, "figure_4b_asymmetric_junction_potential.png")

TABLE4 = pd.DataFrame({
    "Case": [
        r"$N_a = N_d = 1 \times 10^{16}\ \mathrm{cm}^{-3}$",
        r"$N_a = N_d = 1 \times 10^{18}\ \mathrm{cm}^{-3}$",
        r"$N_a = N_d = 1 \times 10^{20}\ \mathrm{cm}^{-3}$",
        r"$N_a = 1 \times 10^{18},\ N_d = 1 \times 10^{16}\ \mathrm{cm}^{-3}$",
    ],
    "eps_max_V_per_m": [5e4, 2e5, 8e5, 3e5],
    "eps_rms_V_per_m": [3e4, 1e5, 5e5, 2e5],
})

def make_table_4_and_figure_5():
    TABLE4.to_csv(TABLES / "table_4_article_values.csv", index=False)
    (TABLES / "table_4_article_values.md").write_text(TABLE4.to_markdown(index=False), encoding="utf-8")

    labels = [r"$10^{16}$", r"$10^{18}$", r"$10^{20}$", r"$10^{18},10^{16}$"]
    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(6.1, 4.8))
    ax.bar(x - width / 2, TABLE4["eps_max_V_per_m"], width=width, color="blue", label=r"$\varepsilon_{\max}$")
    ax.bar(x + width / 2, TABLE4["eps_rms_V_per_m"], width=width, color="red", label=r"$\varepsilon_{\mathrm{RMS}}$")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45)
    ax.set_xlabel(r"$N_a, N_d$ (cm$^{-3}$)")
    ax.set_ylabel("Error (V/m)")
    ax.legend()
    ax.grid(True, axis="y", alpha=0.28)
    savefig(fig, "figure_5_bar_chart_from_table_4.png")

def make_figure_6():
    fractions = np.array([0.010, 0.015, 0.020, 0.030, 0.050, 0.070, 0.10, 0.13, 0.18, 0.25, 0.35, 0.50])
    errors = np.array([1.05e7, 1.05e7, 1.05e7, 1.05e7, 1.05e7, 1.05e7, 1.03e7, 9.9e6, 9.1e6, 7.7e6, 5.0e6, 0.1e6])

    df = pd.DataFrame({
        "smoothing_fraction_f": fractions,
        "eps_rms_V_per_m": errors,
    })
    df.to_csv(TABLES / "figure_6_data.csv", index=False)

    fig, ax = plt.subplots(figsize=(6.6, 4.8))
    ax.plot(fractions, errors, marker="o", linewidth=1.7)
    ax.set_xscale("log")
    ax.set_xlabel(r"Smoothing fraction, $f$ in $\delta = f \cdot W$")
    ax.set_ylabel(r"RMS Error vs Reference, $\varepsilon_{\mathrm{RMS}}$ (V/m)")
    ax.grid(True, which="both", alpha=0.28)
    savefig(fig, "figure_6_sensitivity_to_smoothing_parameter.png")

TABLE5 = pd.DataFrame({
    "Group": ["Experimental (n = 30)", "Comparison (n = 20)"],
    "Mean score before module": ["62%", "60%"],
    "Mean score after module": ["85%", "75%"],
})

def export_table_5():
    TABLE5.to_csv(TABLES / "table_5_classroom_outcomes.csv", index=False)
    (TABLES / "table_5_classroom_outcomes.md").write_text(TABLE5.to_markdown(index=False), encoding="utf-8")

def write_summary():
    lines = [
        "Generated files:",
        "- Figure 1a, 1b, 2, 3a, 3b, 4a, 4b, 5, 6",
        "- Table 4 CSV/Markdown",
        "- Table 5 CSV/Markdown",
        "",
        "Important note:",
        "Figures 3, 4, and 6 were reproduced to match the published visual appearance.",
        "Figures 1 and 2 were generated directly from the article formulas.",
        "Figure 5 is the bar chart that is actually printed in the paper, even though the caption mentions delta-sensitivity.",
    ]
    (ROOT / "ARTICLE_REPRODUCTION_NOTES.txt").write_text("\n".join(lines), encoding="utf-8")

def main():
    make_figure_1()
    make_figure_2()
    make_figure_3()
    make_figure_4()
    make_table_4_and_figure_5()
    make_figure_6()
    export_table_5()
    write_summary()
    print("Done. Figures saved in ./plots_article and tables saved in ./tables_article")

if __name__ == "__main__":
    main()