# -*- coding: utf-8 -*-
"""Untitled221.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfOf96FzJoKXRljibuOHklNkINIXd_8i
"""

import matplotlib.pyplot as plt
import numpy as np

# Create figure
fig, ax = plt.subplots(figsize=(10, 4))

# Regions
ax.axvspan(-5, -1, color="#fdecea", label="p-region")
ax.axvspan(1, 5, color="#e8f4fd", label="n-region")
ax.axvspan(-1, 1, color="#eeeeee", alpha=0.8, label="Depletion region")

# Fixed charges (schematic)
y_pos = 0.3
for x in np.linspace(-0.8, -0.2, 4):
    ax.text(x, y_pos, "−", fontsize=18, ha="center", va="center")
for x in np.linspace(0.2, 0.8, 4):
    ax.text(x, y_pos, "+", fontsize=18, ha="center", va="center")

ax.text(0, 0.6, "Fixed charges", ha="center", fontsize=10)

# Electric field arrow
ax.arrow(0.8, -0.4, -1.6, 0,
         head_width=0.08, head_length=0.15,
         length_includes_head=True, color="black")
ax.text(0, -0.55, "Electric field $\\vec{E}$", ha="center", fontsize=10)

# Capacitor analogy
ax.plot([-0.9, -0.9], [-1, -0.7], color="black", linewidth=2)
ax.plot([0.9, 0.9], [-1, -0.7], color="black", linewidth=2)
ax.text(0, -1.1, "Capacitor analogy", ha="center", fontsize=10)

# Labels
ax.text(-3, 0.9, "p-region", ha="center", fontsize=11)
ax.text(3, 0.9, "n-region", ha="center", fontsize=11)
ax.text(0, 0.9, "Depletion region", ha="center", fontsize=11)

# Axes formatting
ax.set_xlim(-5, 5)
ax.set_ylim(-1.4, 1.2)
ax.set_yticks([])
ax.set_xlabel("Position $x$")
ax.set_title("Conceptual model of a p–n junction and capacitor analogy")

# Legend
ax.legend(loc="upper right", frameon=False)

plt.tight_layout()
plt.show()